# Generated by Django 6.0.8 on 2026-09-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("rack_id", models.IntegerField(blank=True, null=True)),
                (
                    "effective_price",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("price_min", models.DecimalField(decimal_places=4, max_digits=10)),
                ("price_max", models.DecimalField(decimal_places=4, max_digits=10)),
                ("price_observation_count", models.IntegerField()),
                ("source_row_count", models.IntegerField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "geocode_source",
                    models.CharField(default="unresolved", max_length=50),
                ),
                (
                    "geocode_precision",
                    models.CharField(default="unresolved", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["opis_id"],
            },
        ),
    ]
